sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t offtechnologies/docker-arm32v6-bind .
# test image
#- docker run offtechnologies/docker-arm32v6-bind uname -a
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ARG BIND_VERSION" Dockerfile | awk -F "=" 'NF>1{print $NF}')
    docker tag offtechnologies/docker-arm32v6-bind offtechnologies/docker-arm32v6-bind:$TAG
    docker push offtechnologies/docker-arm32v6-bind:$TAG
    docker push offtechnologies/docker-arm32v6-bind
  fi
